namespace :ingredients do
  desc "Ingredient Generator"
  task :generate => :environment do
    ingredient_names = ["Ail",
      "Algues",
      "Artichaut",
      "Asperge",
      "Aubergine",
      "Avocat",
      "Betterave",
      "Blette",
      "Brocoli",
      "Carotte",
      "Céleri",
      "Céléri rave",
      "Champignon",
      "Choux",
      "Choux fleur",
      "Choux rouge",
      "Citrouille",
      "Concombre",
      "Coriandre",
      "Germinations",
      "Courgette",
      "Echalote",
      "Endive",
      "Epinard",
      "Fenouil",
      "Flageolet",
      "Haricot",
      "Laitue",
      "Lentille",
      "Lentille corail",
      "Maïs",
      "Navet",
      "Oignon",
      "Panais",
      "Patate",
      "Persil",
      "Poireau",
      "Pois chiche",
      "Poivron",
      "Potimarron",
      "Potiron",
      "Radis",
      "Rhubarbe",
      "Salade",
      "Salsifi",
      "Tomate",
      "Amandes",
      "Abricot",
      "Ananas",
      "Avocat",
      "Banane",
      "Cassis",
      "Cerise",
      "Châtaigne",
      "Citron",
      "Clémentine",
      "Coing",
      "Datte",
      "Figue",
      "Fraise",
      "Framboise",
      "Groseille",
      "Kaki",
      "Kiwi",
      "Lime",
      "Litchi",
      "Mandarine",
      "Mangue",
      "Melon",
      "Menthe",
      "Mûre",
      "Myrtille",
      "Nectarine",
      "Noisette",
      "Noix",
      "Noix de coco",
      "Olive",
      "Orange",
      "Pamplemousse",
      "Papaye",
      "Pastèque",
      "Pêche",
      "Pistache",
      "Poire",
      "Pomme",
      "Prune",
      "Pruneau",
      "Quetsche",
      "Raisin",
      "Raisins secs",
      "lait",
      "yaourt",
      "fromage blanc",
      "fromage rape",
      "fromage",
      "Parmesan",
      "beurre",
      "flan",
      "œufs",
      "creme fraiche",
      "pates",
      "riz blanc",
      "riz complet",
      "Miso",
      "farine blé blanche",
      "farine blé complete",
      "farine seigle claire",
      "farine epautre comp",
      "farine epautre blanc",
      "farine riz",
      "sesame",
      "polenta",
      "sarasin",
      "quinoa",
      "couscous",
      "pois chiches",
      "sucre",
      "proteine soja granulat",
      "graines salade",
      "falafel",
      "saussice vegy",
      "tofu",
      "Chocolat",
      "eau",
      "thé",
      "cafe",
      "levure",
      "sel fin",
      "huile olive",
      "huile tournesol",
      "sauce tomate",
      "moutarde",
      "confiture",
      "miel",
      "Bouillon legumes",
      "Poivre",
      "Badiane",
      "Cannelle",
      "Cardamome",
      "Basilic",
      "Colombo",
      "Coriandre",
      "Cumin",
      "Curcuma",
      "Curry",
      "eau fleur oranger",
      "Garam Masala",
      "Genievre",
      "Gingembre",
      "Girofle",
      "menthe",
      "Moutarde graines",
      "Muscade",
      "Paprika",
      "Pavot",
      "Piment",
      "Ras el Hanout",
      "Safran",
      "Sésame",
      "Vanille",
      "Vinaigre",
      "Vin"
    ]

    ingredient_names.each do |ing_name|
      Ingredient.create(name: ing_name)
    end
  end
end