development:
  adapter: postgresql
  encoding: unicode
  database: zen_menu_development
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: zen_menu_test
  pool: 5
  password:
  min_messages: WARNING
  host: localhost